### ISSUE TITLE
Stats not working for custom domains

### ISSUE THREAD

**Issue by joaoramos** [thedevs-network/kutt#200]
Although total clicks are properly shown as "Total clicks" in the homepage and in the chart header, the chart isn't showing any stats. As you can see below, I'm getting "Total clicks: 4" followed by a "0 tracked clicks all time." I'm using a custom domain.

![no-stats](https://user-images.githubusercontent.com/1187347/61626352-0534ac80-ac75-11e9-9d38-9caf3a7210fa.gif)

**Comment by joshhopkins** [comment]
Just about to report the same issue.

**Comment by FlorianLudwig** [comment]
It seems to be the case when using a custom domain. We have an instance of kutt running and got statics on the main domain but not on custom domains.

**Comment by joaoramos** [comment]
Updated title and description to make it explicit that this only applies to custom domains.

**Comment by FlorianLudwig** [comment]
The stats component only gets the id, not the customDomain and so requests the wrong stats: 

https://github.com/thedevs-network/kutt/blob/develop/client/components/Stats/Stats.js#L91

But even when including `domain=` in the query I still get no stats.  From quick look into the code I couldn't determine why though

https://github.com/thedevs-network/kutt/blob/91805e14b46a1062aab2c124ea837a101fe4ac8c/server/controllers/urlController.js#L289-L308

**Comment by hi-too** [comment]
I guess, it will be updated in some time.. after some stats being processed.

**Comment by poeti8** [comment]
This has been fixed in v2. And @hi-too is correct, stats are being cached you can see the last time they have been updated under the title.

**Comment by Couto** [comment]
This is not entirely fixed yet, at least with a custom domain.

- It's losing clicks. I visited a link twice, but only 1 click is shown in the total clicks.
- The graph used to display the first click, but it suddenly disappeared.

![Screen Shot 2019-12-24 at 10 59 12](https://user-images.githubusercontent.com/165314/71410296-98b34480-263c-11ea-92a3-45c24a914add.png)

**Comment by poeti8** [comment]
@Couto Stats are being cached, you can see the last updated time under the stats title.

**Comment by Couto** [comment]
> @Couto Stats are being cached, you can see the last updated time under the stats title.

Sure, that's fair. 
But I also have stats that suddenly disappeared. Is that known?

**Comment by poeti8** [comment]
@Couto Nope, stats count should match the one being shown in the table.

**Comment by Couto** [comment]
@poeti8 yeah, after the first visit, it matched 1 click, which was displayed in the table, but then suddenly everything disappeared :(

**Comment by poeti8** [comment]
@Couto That... shouldn't happen. I guess I can't look into that link to debug because more people clicked on it, so can you shorten sample links and try again and let me if it happens so I can investigate?

**Comment by Couto** [comment]
Oh.. you can look at the link: http://utom.is/gh which redirects to https://github.com it was a link to test the service :)

**Comment by poeti8** [comment]
@Couto Found the sneaky bug 🐞. Pushed a fix, should be good now!
